cmake -DCMAKE_BUILD_TYPE=Release \
-DMFIX_MPI=NO \
-DMFIX_OMP=NO \
-DMFIX_GPU_BACKEND=CUDA \
-DAMReX_MPI=NO \
-DAMReX_OMP=NO \
-DAMReX_GPU_BACKEND=CUDA \
-DAMReX_CUDA_ARCH=AUTO \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
..