MFIX = ../../
AMREX_HOME ?= $(MFIX)/subprojects/amrex/

TOP = .

EBASE := mfix.unit-test.fluid_var

BL_NO_FORT = TRUE

DEBUG    = FALSE
DEBUG    = TRUE

DIM = 3

COMP = gcc

USE_PARTICLES = FALSE
USE_EB        = TRUE
USE_MG        = FALSE

PRECISION = DOUBLE

USE_MPI  = FALSE
USE_OMP  = FALSE
USE_CUDA = FALSE

include ./source/Make.fluid_var
