MFIX ?= ../../
AMREX_HOME ?= ../../subprojects/amrex/

TOP = .

EBASE := mfix-distributions.unit-test

BL_NO_FORT = TRUE

DEBUG    = FALSE
DEBUG    = TRUE

DIM = 3

COMP = gcc

USE_PARTICLES = FALSE

PRECISION = DOUBLE

USE_MPI  = TRUE
USE_OMP  = FALSE
USE_CUDA = FALSE

USE_HDF5  = FALSE
USE_HDF5_ZFP = FALSE

include ./source/Make.dist
